name: Local Qwen
version: 0.0.1
schema: v1

models:
  - name: qwen2.5-coder 7B
    provider: ollama
    model: qwen2.5-coder:7b
    apiBase: http://localhost:11434
    roles:
      - chat
      - edit
      - apply
    capabilities:
      - tool_use
    defaultCompletionOptions:
      contextLength: 8192
      temperature: 0